name: macOS

on:
  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setting up
      run: make setup
    - name: "Building with default compiler (Clang++)"
      run: make build
    - name: 'Export binary'
      uses: actions/upload-artifact@v2
      with:
          name: app
          path: bin/mac/app
    - name: Cleaning up for fresh build
      run: make clean
    - name: "Building with GCC/G++"
      run: make build CXX=g++
    - name: Final cleaning
      run: make clean && make clean-lib
