name: Windows

on:
  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setting up
      run: mingw32-make setup
      shell: cmd
    - name: Building with default compiler (G++/GCC)
      run: mingw32-make build
      shell: cmd
    - name: 'Export binary'
      uses: actions/upload-artifact@v2
      with:
          name: app.exe
          path: bin/windows/app.exe
    - name: "Cleaning up for freesh build"
      run: mingw32-make clean
      shell: cmd
    - name: "Building with Clang++"
      run: mingw32-make build CXX=clang++
      shell: cmd
    - name: "Final cleaning"
      run: mingw32-make clean && mingw32-make clean-lib
      shell: cmd
